In [1]:
import pandas as pd

In [3]:
# import the dataset
train = pd.read_csv('Dataset/Additional_Country_level_data.csv')

In [4]:
train.head()

,countid,country,year,popsize,PMI,amountPMI(Per capita aid disbursement),"PEPFAR (1=yes, 0=no)",OtherDAHPMI,Neonatal,average Plasmodium falciparum rate in 2-10 years old in 2005 MAP,GNI per capita in 2004-2014 (PPP),Voice and accountability,RegulatoryQuality,RuleOfLaw,health expenditure in 2004-2014,RuralPopulation,government effectiveness index in 2005,political stability index in 2004-2005,corruption index,GovEffectiveness
0,1,Angola,2004,18865716,0,0,0,57720079,56.700001,0.2909,2610,-1.28,-1.25,-1.46,153.300674,64.595001,NaN,-1.04,-1.28,-1.28
1,1,Angola,2005,19552542,1,1740000,0,138584938,56.099998,0.2790,3010,-1.24,-1.29,-1.44,157.521164,63.831001,NaN,-0.89,-1.33,-1.17
2,1,Angola,2006,20262399,1,7500000,0,57234955,55.500000,0.2461,3600,-1.23,-1.12,-1.29,209.614838,63.057999,NaN,-0.54,-1.18,-1.35
3,1,Angola,2007,20997687,1,18500000,1,64829857,55.000000,0.1916,4480,-1.17,-1.03,-1.39,189.901871,62.278000,NaN,-0.70,-1.29,-1.23
4,1,Angola,2008,21759420,1,18846000,1,95637080,54.099998,0.1242,4810,-1.13,-1.06,-1.39,242.154266,61.491001,NaN,-0.35,-1.28,-1.07

In [5]:
# Remove duplicate rows from the DataFrame
train = train.drop_duplicates()

In [6]:
# delete the government effectiveness index in 2005 column since all its values are undefined
train.drop('government effectiveness index in 2005', axis=1, inplace=True)

In [8]:
# Confirm that the column has been removed
train.head()

,countid,country,year,popsize,PMI,amountPMI(Per capita aid disbursement),"PEPFAR (1=yes, 0=no)",OtherDAHPMI,Neonatal,average Plasmodium falciparum rate in 2-10 years old in 2005 MAP,GNI per capita in 2004-2014 (PPP),Voice and accountability,RegulatoryQuality,RuleOfLaw,health expenditure in 2004-2014,RuralPopulation,political stability index in 2004-2005,corruption index,GovEffectiveness
0,1,Angola,2004,18865716,0,0,0,57720079,56.700001,0.2909,2610,-1.28,-1.25,-1.46,153.300674,64.595001,-1.04,-1.28,-1.28
1,1,Angola,2005,19552542,1,1740000,0,138584938,56.099998,0.2790,3010,-1.24,-1.29,-1.44,157.521164,63.831001,-0.89,-1.33,-1.17
2,1,Angola,2006,20262399,1,7500000,0,57234955,55.500000,0.2461,3600,-1.23,-1.12,-1.29,209.614838,63.057999,-0.54,-1.18,-1.35
3,1,Angola,2007,20997687,1,18500000,1,64829857,55.000000,0.1916,4480,-1.17,-1.03,-1.39,189.901871,62.278000,-0.70,-1.29,-1.23
4,1,Angola,2008,21759420,1,18846000,1,95637080,54.099998,0.1242,4810,-1.13,-1.06,-1.39,242.154266,61.491001,-0.35,-1.28,-1.07

In [9]:
# Get columns with string data
categorical_cols = [cname for cname in train.columns if train[cname].dtype == "object"]

In [10]:
categorical_cols

['country']

In [13]:
# Perfom label encoding on categorical data
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_train = train.copy()
label_train['country'] = label_encoder.fit_transform(train['country'])

In [15]:
label_train.head()

,countid,country,year,popsize,PMI,amountPMI(Per capita aid disbursement),"PEPFAR (1=yes, 0=no)",OtherDAHPMI,Neonatal,average Plasmodium falciparum rate in 2-10 years old in 2005 MAP,GNI per capita in 2004-2014 (PPP),Voice and accountability,RegulatoryQuality,RuleOfLaw,health expenditure in 2004-2014,RuralPopulation,political stability index in 2004-2005,corruption index,GovEffectiveness
0,1,0,2004,18865716,0,0,0,57720079,56.700001,0.2909,2610,-1.28,-1.25,-1.46,153.300674,64.595001,-1.04,-1.28,-1.28
1,1,0,2005,19552542,1,1740000,0,138584938,56.099998,0.2790,3010,-1.24,-1.29,-1.44,157.521164,63.831001,-0.89,-1.33,-1.17
2,1,0,2006,20262399,1,7500000,0,57234955,55.500000,0.2461,3600,-1.23,-1.12,-1.29,209.614838,63.057999,-0.54,-1.18,-1.35
3,1,0,2007,20997687,1,18500000,1,64829857,55.000000,0.1916,4480,-1.17,-1.03,-1.39,189.901871,62.278000,-0.70,-1.29,-1.23
4,1,0,2008,21759420,1,18846000,1,95637080,54.099998,0.1242,4810,-1.13,-1.06,-1.39,242.154266,61.491001,-0.35,-1.28,-1.07

In [16]:
# Perform feature scaling on the data
from sklearn.preprocessing import StandardScaler

In [17]:
ss = StandardScaler()
scaled_train = ss.fit_transform(label_train)

In [18]:
scaled_train

array([[-1.67874412, -1.67874412, -1.58113883, ..., -0.54754785,
        -1.2362578 , -1.08182281],
       [-1.67874412, -1.67874412, -1.26491106, ..., -0.35790843,
        -1.34913463, -0.82609517],
       [-1.67874412, -1.67874412, -0.9486833 , ...,  0.08458345,
        -1.01050415, -1.24455868],
       ...,
       [ 1.67874412,  1.67874412,  0.9486833 , ..., -0.23148221,
        -1.37171   , -1.1980628 ],
       [ 1.67874412,  1.67874412,  1.26491106, ..., -0.0924133 ,
        -1.52973756, -1.05857487],
       [ 1.67874412,  1.67874412,  1.58113883, ..., -0.0924133 ,
        -1.48458683, -0.87259133]])